FROM quay.io/eggplantsoftware/epgw:25.3.2-0046

RUN apt-get update \
&& apt-get install -y --no-install-recommends libturbojpeg libavformat58 libswscale5 curl ca-certificates \
&& rm -rf /var/lib/apt/lists/*

WORKDIR /root

ENV ASPNETCORE_Kestrel__Endpoints__Http__Url "http://0.0.0.0:8080"

EXPOSE 8080

ENTRYPOINT [ "/opt/epgw/epgw" ]
